export const INDEX_COMPANIES = 'companies'
export const INDEX_PERSONS = 'persons'
export const INDEX_HISTORY = 'history'
export const INDEX_FILES = 'processed-files'
export const INDEX_VEHICLES = 'vehicles'
export const INDEX_INCIDENTS = 'incidents'

export const BUCKET_FILES = 'files'
export const BUCKET_IMAGES = 'images'
export const BUCKET_REPORTS = 'reports'
