service: osint

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  scraper-termene:
    handler: dist/apps/scraper-termene/main.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'