name: Validate Reports Service

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/cli/**'
      - 'libs/**'
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --strict-peer-dependencies --no-optional

      - name: Run linter
        run: pnpm lint

      - name: Build Indexer service
        run: pnpm build reports