export const QUEUE_GRAPH_PERSONS = 'graph_persons'
export const QUEUE_GRAPH_COMPANIES = 'graph_companies'
export const QUEUE_GRAPH_FILES = 'graph_files'
export const QUEUE_GRAPH_EVENTS = 'graph_events'
export const QUEUE_GRAPH_PROPERTIES = 'graph_properties'
export const QUEUE_GRAPH_REPORTS = 'graph_reports'
