import { Global, Module } from '@nestjs/common'
import { MongooseModule } from '@nestjs/mongoose'

import {
  AssociateModel,
  AssociateSchema,
  CompanyHistorySnapshotModel,
  CompanyHistorySnapshotSchema,
  CompanyModel,
  CompanyPendingSnapshotModel,
  CompanyPendingSnapshotSchema,
  CompanySchema,
  CoordinatesModel,
  CoordinatesSchema,
  CustomFieldModel,
  CustomFieldSchema,
  DataRefModel,
  DataRefSchema,
  DateValueWithMetadataModel,
  DateValueWithMetadataSchema,
  EducationModel,
  EducationSchema,
  EventHistorySnapshotModel,
  EventHistorySnapshotSchema,
  EventModel,
  EventPendingSnapshotModel,
  EventPendingSnapshotSchema,
  EventSchema,
  FileModel,
  FileSchema,
  IdDocumentModel,
  IdDocumentSchema,
  LinkModel,
  LinkSchema,
  LocationModel,
  LocationSchema,
  MetadataModel,
  MetadataSchema,
  NumberValueWithMetadataModel,
  NumberValueWithMetadataSchema,
  OldNameModel,
  OldNameSchema,
  OptionalDateValueWithMetadataModel,
  OptionalDateValueWithMetadataSchema,
  PartyModel,
  PartySchema,
  PersonHistorySnapshopModel,
  PersonHistorySnapshopSchema,
  PersonModel,
  PersonPendingSnapshopSchema,
  PersonPendingSnapshotModel,
  PersonSchema,
  ProceedingEntityModel,
  ProceedingEntitySchema,
  ProceedingHistorySnapshotModel,
  ProceedingHistorySnapshotSchema,
  ProceedingModel,
  ProceedingPendingSnapshotModel,
  ProceedingPendingSnapshotSchema,
  ProceedingSchema,
  PropertyHistorySnapshotModel,
  PropertyHistorySnapshotSchema,
  PropertyModel,
  PropertyOwnerModel,
  PropertyOwnerSchema,
  PropertyPendingSnapshotModel,
  PropertyPendingSnapshotSchema,
  PropertySchema,
  RelationshipModel,
  RelationshipSchema,
  ReportContentModel,
  ReportContentSchema,
  ReportHistorySnapshotModel,
  ReportHistorySnapshotSchema,
  ReportModel,
  ReportPendingSnapshotModel,
  ReportPendingSnapshotSchema,
  ReportSchema,
  ReportSectionModel,
  ReportSectionSchema,
  TableModel,
  TableSchema,
  TextModel,
  TextSchema,
  TextValueWithMetadataModel,
  TextValueWithMetadataSchema,
  TitleModel,
  TitleSchema,
  TrustModel,
  TrustSchema,
} from './models'

import { ProceedingsService } from '@app/models/services/proceedingsService'
import { LocationsService } from '@app/models/services/locationsService'
import { CompaniesService } from '@app/models/services/companiesService'
import { FilesService } from '@app/models/services/filesService'
import { EventsService } from '@app/models/services/eventsService'
import { PersonsService } from '@app/models/services/personsService'
import { PropertiesService } from '@app/models/services/propertiesService'
import { ReportsService } from '@app/models/services/reportsService'

@Global()
@Module({
  imports: [
    MongooseModule.forFeature([
      { name: TrustModel.name, schema: TrustSchema },
      { name: MetadataModel.name, schema: MetadataSchema },
      { name: TextValueWithMetadataModel.name, schema: TextValueWithMetadataSchema },
      { name: NumberValueWithMetadataModel.name, schema: NumberValueWithMetadataSchema },
      { name: DateValueWithMetadataModel.name, schema: DateValueWithMetadataSchema },
      {
        name: OptionalDateValueWithMetadataModel.name,
        schema: OptionalDateValueWithMetadataSchema,
      },
      { name: FileModel.name, schema: FileSchema },
      { name: LocationModel.name, schema: LocationSchema },
      { name: CoordinatesModel.name, schema: CoordinatesSchema },
      { name: CustomFieldModel.name, schema: CustomFieldSchema },
      { name: PersonModel.name, schema: PersonSchema },
      { name: PersonHistorySnapshopModel.name, schema: PersonHistorySnapshopSchema },
      { name: PersonPendingSnapshotModel.name, schema: PersonPendingSnapshopSchema },
      { name: OldNameModel.name, schema: OldNameSchema },
      { name: IdDocumentModel.name, schema: IdDocumentSchema },
      { name: RelationshipModel.name, schema: RelationshipSchema },
      { name: EducationModel.name, schema: EducationSchema },
      { name: CompanyModel.name, schema: CompanySchema },
      { name: CompanyHistorySnapshotModel.name, schema: CompanyHistorySnapshotSchema },
      { name: CompanyPendingSnapshotModel.name, schema: CompanyPendingSnapshotSchema },
      { name: AssociateModel.name, schema: AssociateSchema },
      { name: EventModel.name, schema: EventSchema },
      { name: EventHistorySnapshotModel.name, schema: EventHistorySnapshotSchema },
      { name: EventPendingSnapshotModel.name, schema: EventPendingSnapshotSchema },
      { name: PartyModel.name, schema: PartySchema },
      { name: PropertyModel.name, schema: PropertySchema },
      { name: PropertyHistorySnapshotModel.name, schema: PropertyHistorySnapshotSchema },
      { name: PropertyPendingSnapshotModel.name, schema: PropertyPendingSnapshotSchema },
      { name: PropertyOwnerModel.name, schema: PropertyOwnerSchema },
      { name: ProceedingModel.name, schema: ProceedingSchema },
      { name: ProceedingHistorySnapshotModel.name, schema: ProceedingHistorySnapshotSchema },
      { name: ProceedingPendingSnapshotModel.name, schema: ProceedingPendingSnapshotSchema },
      { name: ProceedingEntityModel.name, schema: ProceedingEntitySchema },
      { name: ReportModel.name, schema: ReportSchema },
      { name: ReportHistorySnapshotModel.name, schema: ReportHistorySnapshotSchema },
      { name: ReportPendingSnapshotModel.name, schema: ReportPendingSnapshotSchema },
      { name: ReportSectionModel.name, schema: ReportSectionSchema },
      { name: ReportContentModel.name, schema: ReportContentSchema },
      { name: LinkModel.name, schema: LinkSchema },
      { name: TableModel.name, schema: TableSchema },
      { name: TextModel.name, schema: TextSchema },
      { name: TitleModel.name, schema: TitleSchema },
      { name: DataRefModel.name, schema: DataRefSchema },
    ]),
  ],
  providers: [
    PersonsService,
    CompaniesService,
    FilesService,
    EventsService,
    PropertiesService,
    ReportsService,
    LocationsService,
    ProceedingsService,
  ],
  exports: [
    MongooseModule,
    PersonsService,
    CompaniesService,
    FilesService,
    EventsService,
    PropertiesService,
    ReportsService,
    LocationsService,
    ProceedingsService,
  ],
})
export class EntitiesModule {}
