export const QUEUE_PERSONS = 'persons'
export const QUEUE_COMPANIES = 'companies'
export const QUEUE_FILES = 'files'
export const QUEUE_INCIDENTS = 'incidents'
export const QUEUE_PROPERTIES = 'properties'
export const QUEUE_REPORTS = 'reports'

export const EVENT_UPDATED = 'update'
export const EVENT_CREATED = 'create'
export const EVENT_VIEWED = 'view'
export const EVENT_DOWNLOAD = 'download'
