name: Build Frontend Staging Image

on:
  push:
    branches: [ staging ]
    paths:
      - '.github/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'apps/frontend/**'
      - 'packages/defs/**'

env:
  REGISTRY: "192.168.1.128:49153/bi-link"
  IMAGE_NAME: "link-frontend"

jobs:
  build_image:
    runs-on: self-hosted
    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2

      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):staging --target staging -f ./apps/frontend/Dockerfile .

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):staging

      - uses: colpal/actions-clean@v1
        if: ${{ always() }}