name: Build Backend Prod Image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build_backend.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'apps/backend-services/**'
      - 'packages/defs/**'

permissions:
  packages: write

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/Larion-Design/publish-packages/link-backend
          tags: type=sha

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: backend
          cache-from: type=gha
          cache-to: type=gha,mode=max