name: Build Frontend Staging Image

on:
  push:
    branches: [ staging ]
    paths:
      - '.github/workflows/build_frontend_staging.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'apps/frontend/**'
      - 'packages/defs/**'

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/Larion-Design/link-frontend
          tags: type=sha

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ghcr.io/Larion-Design/link-frontend:staging
          target: frontend-staging
          cache-from: type=gha
          cache-to: type=gha,mode=max