name: Build Backend Prod Image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'apps/backend-services/**'
      - 'packages/defs/**'

env:
  REGISTRY: "registry.digitalocean.com/bi-link"
  IMAGE_NAME: "link-backend"

jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME) -f ./apps/backend-services/Dockerfile .

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME)

      - name: Cleanup
        run: docker image rm $(echo $REGISTRY)/$(echo $IMAGE_NAME) -f

#      - name: Cleanup
#        run: docker image prune # docker rmi -f $(docker images -aq) || true