name: Validate PR Changes

on:
  pull_request:
    branches: [ main, staging ]
    types: [opened, synchronize]

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build project
        run: pnpm build