export const MICROSERVICES = {
  GLOBAL: {
    id: 'GLOBAL',
    entityCreated: 'entityCreated',
    entityModified: 'entityModified',
    entitiesRefreshed: 'entitiesRefreshed',
  },
  INGRESS: {
    id: 'INGRESS',
    getEntity: 'getEntity',
    getEntities: 'getEntities',
    getAllEntities: 'getAllEntities',
    createEntity: 'createEntity',
    updateEntity: 'updateEntity',
    createPendingSnapshot: 'createPendingSnapshot',
    removePendingSnapshot: 'removePendingSnapshot',
    getPendingSnapshot: 'getPendingSnapshot',
    getPendingSnapshotsById: 'getPendingSnapshotsById',
    getPendingSnapshotsByEntity: 'getPendingSnapshotsByEntity',
    getHistorySnapshot: 'getHistorySnapshot',
    getHistorySnapshotsById: 'getHistorySnapshotsById',
    getHistorySnapshotsByEntity: 'getHistorySnapshotsByEntity',
    createHistorySnapshot: 'createHistorySnapshot',
    applyPendingSnapshot: 'applyPendingSnapshot',
    revertHistorySnapshot: 'revertHistorySnapshot',
    getFileByHash: 'getFileByHash',
    getReportsTemplates: 'getReportsTemplates',
    findCompanyId: 'findCompanyId',
    findPersonId: 'findPersonId',
    findProceedingId: 'findProceedingId',
  },
  ACTIVITY_HISTORY: {
    id: 'ACTIVITY_HISTORY',
    recordAction: 'recordAction',
    getActivityEvents: 'getActivityEvents',
  },
  INDEXER: {
    id: 'INDEXER',
    search: 'search',
    indexEntity: 'indexEntity',
    getFileContent: 'getFileContent',
    reindexEntities: 'reindexEntities',
    createMapping: 'createMapping',
    recordHistoryEvent: 'addHistoryEvent',
    personCNPExists: 'personCNPExists',
    personIdDocumentExists: 'personIdDocumentExists',
    companyCUIExists: 'companyCUIExists',
    companyRegistrationNumberExists: 'companyRegistrationNumberExists',
    vehicleVINExists: 'vehicleVINExists',
    getVehiclesModels: 'getVehiclesModels',
    getVehiclesMakers: 'getVehiclesMakers',
  },
  GRAPH: {
    id: 'GRAPH',
    refreshNodes: 'refreshNodes',
    getEntityRelationships: 'getEntityRelationships',
  },
  FILES_MANAGER: {
    id: 'FILES_MANAGER',
    uploadFile: 'uploadFile',
    getFileDownloadUrl: 'getFileDownloadUrl',
    getFilesDownloadUrls: 'getFilesDownloadUrls',
    getFileContent: 'getFileContent',
    extractTextFromFile: 'extractTextFromFile',
  },
  OSINT: {
    TERMENE: {
      id: 'TERMENE',
      searchCompaniesByName: 'searchCompaniesByName',
      searchPersons: 'searchPersons',
      searchProceedings: 'searchProceedings',
      importCompany: 'importCompany',
      importPersonCompanies: 'importPersonCompanies',
      importProceeding: 'importProceeding',
    },
  },
}
