export const MICROSERVICES = {
  GLOBAL: {
    id: 'GLOBAL',
    entityCreated: 'entityCreated',
    entityModified: 'entityModified',
    entitiesRefreshed: 'entitiesRefreshed',
  },
  INGRESS: {
    id: 'INGRESS',
    getEntity: 'getEntity',
    getEntities: 'getEntities',
    getAllEntities: 'getAllEntities',
    createEntity: 'createEntity',
    updateEntity: 'updateEntity',
    createPendingSnapshot: 'createPendingSnapshot',
    removePendingSnapshot: 'removePendingSnapshot',
    getPendingSnapshot: 'getPendingSnapshot',
    getPendingSnapshotsById: 'getPendingSnapshotsById',
    getPendingSnapshotsByEntity: 'getPendingSnapshotsByEntity',
    getHistorySnapshot: 'getHistorySnapshot',
    getHistorySnapshotsById: 'getHistorySnapshotsById',
    getHistorySnapshotsByEntity: 'getHistorySnapshotsByEntity',
    createHistorySnapshot: 'createHistorySnapshot',
    applyPendingSnapshot: 'applyPendingSnapshot',
    revertHistorySnapshot: 'revertHistorySnapshot',
    getFileByHash: 'getFileByHash',
  },
  FILES_PARSER: {
    id: 'FILES_PARSER',
    extractText: 'extractText',
  },
  ACTIVITY_HISTORY: {
    id: 'ACTIVITY_HISTORY',
    recordAction: 'recordAction',
    getActivityEvents: 'getActivityEvents',
  },
  ENTITY_EVENTS: {
    id: 'ENTITY_EVENTS',
    entityCreated: 'entityCreated',
    entityModified: 'entityModified',
    entitiesRefresh: 'entitiesRefresh',
  },
  INDEXER: {
    id: 'INDEXER',
    search: 'search',
    indexEntity: 'indexEntity',
    reindexEntities: 'reindexEntities',
    createMapping: 'createMapping',
    recordHistoryEvent: 'addHistoryEvent',
    getFileContent: 'getFileContent',
    personCNPExists: 'personCNPExists',
    personIdDocumentExists: 'personIdDocumentExists',
    companyCUIExists: 'companyCUIExists',
    companyRegistrationNumberExists: 'companyRegistrationNumberExists',
    vehicleVINExists: 'vehicleVINExists',
  },
  GRAPH: {
    id: 'GRAPH',
    refreshNodes: 'refreshNodes',
    getEntityRelationships: 'getEntityRelationships',
  },
  FILES_MANAGER: {
    id: 'FILES_MANAGER',
    uploadFile: 'uploadFile',
    getFileDownloadUrl: 'getFileDownloadUrl',
    getFilesDownloadUrls: 'getFilesDownloadUrls',
  },
  OSINT: {},
}
